version: '3'
services:
    web:
        image: go-docker-web:1.0
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - 3000:3000
        volumes: 
            - .:/root